In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('spotify-2023.csv', thousands=',')
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4.0
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4.0
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6.0
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15.0
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3.0
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6.0
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6.0
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5.0
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5.0

In [14]:
df.dtypes

track_name               object
artist(s)_name           object
artist_count              int64
released_year             int64
released_month            int64
released_day              int64
in_spotify_playlists      int64
in_spotify_charts         int64
streams                   int64
in_apple_playlists        int64
in_apple_charts           int64
in_deezer_playlists       int64
in_deezer_charts          int64
in_shazam_charts        float64
bpm                      object
key                      object
mode                     object
danceability_%            int64
valence_%                 int64
energy_%                  int64
acousticness_%            int64
instrumentalness_%        int64
liveness_%                int64
speechiness_%           float64
dtype: object

In [18]:
a = df[['released_year', 'in_apple_playlists', 'in_deezer_playlists']].groupby('released_year').agg('sum')
a

               in_apple_playlists  in_deezer_playlists
released_year
1930                            4                   14
1942                           73                  123
1946                          140                  251
1950                          126                  406
1952                          108                   73
1957                          197                  169
1958                          400                  416
1959                          153                  318
1963                          417                  634
1968                           71                  653
1970                           21                   10
1971                          130                  390
1973                            0                    5
1975                          621                 6694
1979                            1                   29
1982                          131                 1019
1983                          211                  929
1984                          607                 6864
1985                          218                 3331
1986                          162                  412
1987                          228                 6720
1991                          310                13564
1992                          146                 6807
1994                          387                 2094
1995                          149                 2049
1996                           46                   60
1997                            0                    6
1998                          137                  582
1999                          640                21949
2000                          283                11170
2002                          800                26024
2003                          345                12404
2004                          272                 8086
2005                          108                   30
2007                           30                  588
2008                          296                 5410
2010                          566                11629
2011                         1241                23170
2012                          891                12381
2013                         1824                32545
2014                         1673                12545
2015                         1045                 9893
2016                         2078                14502
2017                         3100                25587
2018                         1474                 7765
2019                         5579                18899
2020                         4388                 9519
2021                        10643                19293
2022                        16479                21896
2023                         5660                 7123

In [20]:
a.shape

(50, 2)